from datetime import datetime
from numbers import Real
from pathlib import Path
import pandas as pd
from openpyxl import Workbook
from openpyxl.chart import BarChart, LineChart, Reference
from openpyxl.formatting.rule import DataBarRule
from openpyxl.styles import Alignment
from openpyxl.worksheet.table import Table, TableStyleInfo
from .analytics import analyse, load_sales
from .theme import *

GBP = '£#,##0.00;[Red]-£#,##0.00'

def _set_widths(ws, widths):
    for col, width in widths.items(): ws.column_dimensions[col].width = width

def _brand_band(ws, title, subtitle, end_col="N"):
    ws.merge_cells(f"A1:{end_col}1"); ws["A1"]="COOKE AUTOMATION SYSTEMS"
    ws.merge_cells(f"A2:{end_col}2"); ws["A2"]=title.upper()
    ws.merge_cells(f"A3:{end_col}3"); ws["A3"]=subtitle
    for cell in (ws["A1"], ws["A2"], ws["A3"]):
        cell.fill=fill(NAVY); cell.alignment=align("center")
    ws["A1"].font=font(11, True, GOLD); ws["A2"].font=font(22, True, WHITE); ws["A3"].font=font(10, False, "C8D3DA")
    ws.row_dimensions[1].height=24; ws.row_dimensions[2].height=38; ws.row_dimensions[3].height=24

def _card(ws, rng, label, value, number_format):
    ws.merge_cells(rng)
    cell=ws[rng.split(":")[0]]
    cell.value=round(float(value), 2) if isinstance(value, Real) and not isinstance(value, int) else value
    cell.number_format=number_format
    cell.fill=fill(PEARL); cell.border=border(); cell.font=font(18, True, NAVY); cell.alignment=align("center")
    start,end=rng.split(":"); label_row=int(''.join(filter(str.isdigit,start)))-1
    start_col=''.join(filter(str.isalpha,start)); end_col=''.join(filter(str.isalpha,end))
    ws.merge_cells(f"{start_col}{label_row}:{end_col}{label_row}")
    lab=ws[f"{start_col}{label_row}"]; lab.value=label.upper(); lab.fill=fill(NAVY); lab.font=font(9,True,GOLD); lab.alignment=align("center")

def _dashboard(wb, a):
    ws=wb.active; ws.title="Executive Summary"; ws.showGridLines=False
    _set_widths(ws,{c:5.2 for c in "ABCDEFGHIJKLMN"}); _brand_band(ws,"Sales Performance Report",f"Executive report • Generated {datetime.now():%d %B %Y at %H:%M}")
    ws.merge_cells("A5:N5"); ws["A5"]="EXECUTIVE SUMMARY"; ws["A5"].font=font(11,True,STEEL); ws["A5"].alignment=align("left")
    _card(ws,"A7:D9","Total revenue",a.revenue,GBP)
    _card(ws,"F7:I9","Orders",a.orders,'#,##0')
    _card(ws,"K7:N9","Average order",a.average_order,GBP)
    _card(ws,"C12:G14","Highest sale",a.highest_sale,GBP)
    _card(ws,"I12:M14","Lowest sale",a.lowest_sale,GBP)
    for r in list(range(7,10))+list(range(12,15)): ws.row_dimensions[r].height=22
    ws.merge_cells("A17:G17"); ws["A17"]="REVENUE BY PRODUCT"; ws["A17"].fill=fill(NAVY); ws["A17"].font=font(10,True,WHITE); ws["A17"].alignment=align("left")
    ws.merge_cells("H17:N17"); ws["H17"]="MONTHLY REVENUE TREND"; ws["H17"].fill=fill(NAVY); ws["H17"].font=font(10,True,WHITE); ws["H17"].alignment=align("left")
    chart=BarChart(); chart.type="bar"; chart.style=10; chart.title=None; chart.legend=None
    chart.add_data(Reference(wb["Analysis"],min_col=2,min_row=12,max_row=11+len(a.by_product)),titles_from_data=False)
    chart.set_categories(Reference(wb["Analysis"],min_col=1,min_row=12,max_row=11+len(a.by_product)))
    chart.height=8.0; chart.width=13.2; chart.x_axis.numFmt='£0,"k"'; chart.graphical_properties=None
    ws.add_chart(chart,"A18")
    line=LineChart(); line.style=13; line.legend=None; line.title=None
    start=12; end=11+len(a.by_month)
    line.add_data(Reference(wb["Analysis"],min_col=10,min_row=start,max_row=end),titles_from_data=False)
    line.set_categories(Reference(wb["Analysis"],min_col=9,min_row=start,max_row=end))
    line.height=8.0; line.width=13.2; line.y_axis.numFmt='£0,"k"'
    ws.add_chart(line,"H18")
    ws.merge_cells("A36:N36"); ws["A36"]="Generated by Cooke Automation Systems  •  Excel Report Generator v2.0"
    ws["A36"].font=font(9,False,STEEL); ws["A36"].alignment=align("right")
    ws.sheet_properties.pageSetUpPr.fitToPage=True; ws.page_setup.orientation="landscape"; ws.page_setup.fitToWidth=1; ws.page_setup.fitToHeight=1; ws.print_area="A1:N36"; ws.sheet_view.zoomScale=85

def _analysis(wb, a):
    ws=wb.create_sheet("Analysis"); ws.showGridLines=False; _set_widths(ws,{"A":24,"B":16,"D":24,"E":16,"G":20,"H":16,"I":16,"J":16})
    _brand_band(ws,"Analysis","Auditable summary tables and report-driving calculations","J")
    ws["A4"]="Total Revenue"; ws["B4"]=round(a.revenue,2); ws["A5"]="Orders"; ws["B5"]=a.orders; ws["A6"]="Average Order"; ws["B6"]=round(a.average_order,2); ws["A7"]="Highest Sale"; ws["B7"]=round(a.highest_sale,2); ws["A8"]="Lowest Sale"; ws["B8"]=round(a.lowest_sale,2)
    for r in range(4,9): ws[f"A{r}"].font=font(10,True,STEEL); ws[f"B{r}"].font=font(11,True,NAVY); ws[f"B{r}"].number_format=GBP if r!=5 else '#,##0'
    blocks=[("A10","Product",a.by_product),("D10","Salesperson",a.by_salesperson),("G10","Region",a.by_region),("I10","Month",a.by_month)]
    for anchor,label,series in blocks:
        c=ws[anchor].column; r=ws[anchor].row
        ws.cell(r,c,label); ws.cell(r,c+1,"Revenue")
        for cell in ws.iter_rows(min_row=r,max_row=r,min_col=c,max_col=c+1):
            for x in cell: x.fill=fill(NAVY); x.font=font(10,True,WHITE); x.alignment=align("left")
        for idx,(name,value) in enumerate(series.items(),r+1): ws.cell(idx,c,name); ws.cell(idx,c+1,round(float(value),2)); ws.cell(idx,c+1).number_format=GBP
        ws.get_range if False else None
        ws.conditional_formatting.add(f"{ws.cell(r+1,c+1).coordinate}:{ws.cell(r+len(series),c+1).coordinate}", DataBarRule(start_type='min',end_type='max',color=STEEL,showValue=True))
    ws.freeze_panes="A10"; ws.sheet_properties.pageSetUpPr.fitToPage=True; ws.page_setup.orientation="landscape"; ws.page_setup.fitToWidth=1; ws.page_setup.fitToHeight=1; ws.print_area=f"A1:J{max(18,11+max(len(a.by_product),len(a.by_salesperson),len(a.by_region),len(a.by_month)))}"; ws.sheet_view.zoomScale=90

def _raw(wb, df):
    ws=wb.create_sheet("Raw Data"); ws.showGridLines=False
    headers=["Order ID","Date","Customer","Salesperson","Product","Region","Revenue"]
    ws.append(headers)
    for row in df.itertuples(index=False): ws.append([row.order_id,row.date.to_pydatetime(),row.customer,row.salesperson,row.product,row.region,round(float(row.revenue),2)])
    for c in ws[1]: c.fill=fill(NAVY); c.font=font(10,True,WHITE); c.alignment=align("center")
    for r in range(2,ws.max_row+1):
        ws.cell(r,2).number_format="dd mmm yyyy"; ws.cell(r,7).number_format=GBP
        if r%2==0:
            for c in ws[r]: c.fill=fill(PEARL)
    tab=Table(displayName="SalesData",ref=f"A1:G{ws.max_row}"); tab.tableStyleInfo=TableStyleInfo(name="TableStyleMedium2",showRowStripes=True,showColumnStripes=False)
    ws.add_table(tab); _set_widths(ws,{"A":13,"B":14,"C":24,"D":18,"E":24,"F":14,"G":16}); ws.freeze_panes="A2"; ws.auto_filter.ref=f"A1:G{ws.max_row}"; ws.sheet_properties.pageSetUpPr.fitToPage=True; ws.page_setup.orientation="landscape"; ws.page_setup.fitToWidth=1; ws.page_setup.fitToHeight=0; ws.print_title_rows="1:1"; ws.sheet_view.zoomScale=90

def _info(wb, source):
    ws=wb.create_sheet("Report Information"); ws.showGridLines=False; _set_widths(ws,{"A":24,"B":60}); _brand_band(ws,"Report Information","Generation details and usage notes","B")
    rows=[("Product","Excel Report Generator"),("Version","2.0.0"),("Source file",str(source)),("Generated",datetime.now().strftime("%d %B %Y at %H:%M")),("Purpose","Turn raw sales exports into a polished, auditable executive workbook."),("Refresh","Run generate_report.py again after replacing the source CSV."),("Privacy","The workbook is created locally; the tool does not transmit data.")]
    for i,(k,v) in enumerate(rows,5): ws.cell(i,1,k).font=font(10,True,STEEL); ws.cell(i,2,v); ws.cell(i,2).alignment=align("left","center",True); ws.row_dimensions[i].height=28

def generate_report(input_path: Path, output_path: Path):
    df=load_sales(input_path); a=analyse(df); wb=Workbook(); _analysis(wb,a); _dashboard(wb,a); _raw(wb,df); _info(wb,input_path)
    wb._sheets=[wb["Executive Summary"],wb["Analysis"],wb["Raw Data"],wb["Report Information"]]
    output_path.parent.mkdir(parents=True,exist_ok=True); wb.save(output_path); return output_path
